HUGGINGFACE_TOKEN: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
SERPAPI_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
DOWNLOAD_DIR: "B://models//Llama-3.2-1B-Instruct-unsloth-bnb-4bit"
MODEL_ID: "unsloth/Llama-3.2-1B-Instruct-unsloth-bnb-4bit"
CHROMA_DB_PATH: "B://ai_data//db"
DATA_DIR: "B://ai_data/docs"